"""empty message

Revision ID: 01117a98be71
Revises: a117078c295c
Create Date: 2022-04-14 23:33:13.027061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01117a98be71'
down_revision = 'a117078c295c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('box', sa.Column('two_factor_email', sa.String(length=300), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('box', 'two_factor_email')
    # ### end Alembic commands ###
