"""empty message

Revision ID: 3a9c65856d7f
Revises: 01117a98be71
Create Date: 2022-04-18 14:18:58.872763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a9c65856d7f'
down_revision = '01117a98be71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('box', sa.Column('qrcode', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('box', 'qrcode')
    # ### end Alembic commands ###
