"""empty message

Revision ID: 48126dcd1cff
Revises: ba027bd1bd2d
Create Date: 2022-04-21 12:31:24.152366

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48126dcd1cff'
down_revision = 'ba027bd1bd2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('box', sa.Column('qrcode_public_id', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('box', 'qrcode_public_id')
    # ### end Alembic commands ###
